/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-01-22

 The MIT License (MIT)
 Copyright (c) 2019 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

/*Maxence Dos Santos,
 * Space Invaders,
 * Embedded C Project*/

/* Includes */
#include "push_button.h"
#include "init.h"
#include "fenetre.h"
#include "caracter.h"
#include "hero_move.h"
#include "hero_shoot.h"


/* Private macro */

/* Private variables */



/* Private function prototypes */

/* Private functions */

/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */

/*Version Test de la structure d'un charactère (héros ou invader)*/
typedef struct {
	uint8_t X;
	uint8_t Y;
	uint8_t skin;
	uint8_t weapon;
} T_car;

//Touche d'interruption du serial_putchar
int8_t usual_touch;

int main(void) {

	T_car invader;
	T_car hero;


	invader.X = 0;
	invader.Y = 0;
	invader.skin = 'X';
	invader.weapon = 'v';

	hero.X = 40;
	hero.Y = 22;
	hero.skin = 'T';
	hero.weapon = '^';

	//J'utilise cette variable au cas où je voudrais utiliser autre chose d'un espace pour créer un effet de "trainéé"
	uint8_t trainee = ' ';


	init();
	start_menu();

	/*Fonction de test d'affichage des ennemis*/
	taste(invader.X, invader.Y, invader.skin);

	h_move(hero.X, hero.Y, hero.skin, hero.weapon, trainee, usual_touch);

//	h_shoot(hero.X, hero.Y, hero.weapon, trainee, usual_touch);



	/*Prototype de la fonction appelée "taste"
	 * while (1) {
	 for (invader.Y = 2; invader.Y < 6; invader.Y += 2) {
	 vt100_move((invader.X = 0), (invader.Y));
	 for (invader.X = 10; invader.X < 71; invader.X++) {
	 vt100_move(invader.X, invader.Y);
	 serial_putchar(invader.skin);
	 }
	 vt100_move((invader.X = 70), (invader.Y += 2));
	 for (invader.X = 70; invader.X >= 10; invader.X--) {
	 vt100_move(invader.X, invader.Y);
	 serial_putchar(invader.skin);
	 }
		}
	 }*/


	/*do {
	 //		start_menu();
	 } while (push_button_is_pressed() == 1);*/

//			test();
	/**
	 *  IMPORTANT NOTE!
	 *  The symbol VECT_TAB_SRAM needs to be defined when building the project
	 *  if code has been located to RAM and interrupts are used.
	 *  Otherwise the interrupt table located in flash will be used.
	 *  See also the <system_*.c> file and how the SystemInit() function updates
	 *  SCB->VTOR register.
	 *  E.g.  SCB->VTOR = 0x20000000;
	 */

	/* TODO - Add your application code here */


	/* Infinite loop */

}

/*
 * Callback used by stm32f4_discovery_audio_codec.c.
 * Refer to stm32f4_discovery_audio_codec.h for more info.
 */
void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size) {
	/* TODO, implement your code here */
	return;
}

/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
uint16_t EVAL_AUDIO_GetSampleCallBack(void) {
	/* TODO, implement your code here */
	return -1;
}
